
name: '日志自动清理'

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

env:
  REF_BRANCH: output  ## 选择一个需要处理的其他分支名，这里选的output分支
  #REF_BRANCH: ${{ github.ref_name }}  ## 处理当前默认主分支时启用(二选一,务必填写正确)

jobs:
  auto-clear:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: '3'
          retain_days: '7'

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.REF_BRANCH }}
      - name: Clearing history commit logs
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email ${{ secrets.GIT_EMAIL }}  ## 去secrets中添加GIT_EMAIL变量，值为GitHub邮箱
          git checkout --orphan latest_branch
          git rm -rf --cached .
          git add -A
          git commit -m "Clear commit"
          git show-ref -q --heads ${{ env.REF_BRANCH }} && git branch -D ${{ env.REF_BRANCH }}
          git branch -m ${{ env.REF_BRANCH }}
          git push -f origin ${{ env.REF_BRANCH }}
